export const rules = [
  {
    match: (body) => body.is_standalone_payment && !(body.is_refund || body.is_refunded) && body.success,
    action: "standAlone",
  },
  {
    match: (body) => (body.is_refund || body.is_refunded) && body.success,
    action: "refund",
  },
  {
    match: (body) => body.is_auth && body.success,
    action: "auth",
  },
  {
    match: (body) => body.is_capture && body.success,
    action: "capture",
  },
  {
    match: (body) => body.is_voided && body.success,
    action: "void",
  },
];

// for (const r of rules) {
//   try {
//     const didMatch = r.match({
//       id: 342287353,
//       pending: false,
//       amount_cents: 20000,
//       success: true,
//       is_auth: false,
//       is_capture: false,
//       is_standalone_payment: false,
//       is_voided: false,
//       is_refunded: false,
//       is_3d_secure: false,
//       integration_id: 4867403,
//       profile_id: 1003973,
//       has_parent_transaction: true,
//       order: {
//         id: 384634501,
//         created_at: "2025-09-12T00:19:39.578216",
//         delivery_needed: false,
//         merchant: {
//           id: 1003973,
//           created_at: "2024-11-02T23:28:30.287504",
//           phones: [Array],
//           company_emails: [Array],
//           company_name: "notyet",
//           state: "",
//           country: "EGY",
//           city: "Cairo",
//           postal_code: "",
//           street: "",
//         },
//         collector: null,
//         amount_cents: 20000,
//         shipping_data: {
//           id: 187813820,
//           first_name: "midoAdmin",
//           last_name: "unknown",
//           street: "NA",
//           building: "NA",
//           floor: "dummy",
//           apartment: "NA",
//           city: "dummy",
//           state: "dummy",
//           country: "dummy",
//           email: "midotareq2@gmail.com",
//           phone_number: "01112151549",
//           postal_code: "NA",
//           extra_description: "",
//           shipping_method: "UNK",
//           order_id: 384634501,
//           order: 384634501,
//         },
//         currency: "EGP",
//         is_payment_locked: false,
//         is_return: false,
//         is_cancel: false,
//         is_returned: false,
//         is_canceled: false,
//         merchant_order_id: "dfb74335-6d3a-494d-98ab-01e2c3e24ca8",
//         wallet_notification: null,
//         paid_amount_cents: 20000,
//         notify_user_with_email: false,
//         items: [[Object]],
//         order_url: "NA",
//         commission_fees: 0,
//         delivery_fees_cents: 0,
//         delivery_vat_cents: 0,
//         payment_method: "tbc",
//         merchant_staff_tag: null,
//         api_source: "OTHER",
//         data: {
//           notification_url:
//             "https://254bb8c64e10.ngrok-free.app/payment/webhook",
//         },
//         payment_status: "PAID",
//       },
//       created_at: "2025-09-12T00:20:46.507760",
//       transaction_processed_callback_responses: [],
//       currency: "EGP",
//       source_data: {
//         pan: "2346",
//         type: "card",
//         tenure: null,
//         sub_type: "MasterCard",
//       },
//       api_source: "OTHER",
//       terminal_id: null,
//       merchant_commission: 0,
//       accept_fees: 0,
//       installment: null,
//       discount_details: [],
//       is_void: false,
//       is_refund: true,
//       data: {
//         klass: "MigsPayment",
//         amount: 20000,
//         acs_eci: "",
//         message: "Approved",
//         batch_no: 20250911,
//         card_num: "512345xxxxxx2346",
//         currency: "EGP",
//         merchant: "TESTMERCH_C_25P",
//         card_type: "MASTERCARD",
//         created_at: "2025-09-11T21:20:47.712721",
//         migs_order: {
//           id: "384634501",
//           amount: 200,
//           status: "REFUNDED",
//           currency: "EGP",
//           chargeback: [Object],
//           creationTime: "2025-09-11T21:20:04.907Z",
//           merchantAmount: 200,
//           lastUpdatedTime: "2025-09-11T21:20:47.549Z",
//           merchantCurrency: "EGP",
//           totalCapturedAmount: 200,
//           totalRefundedAmount: 200,
//           merchantCategoryCode: "7299",
//           totalAuthorizedAmount: 200,
//         },
//         order_info: "384634501",
//         receipt_no: "525421157245",
//         migs_result: "SUCCESS",
//         secure_hash: "",
//         authorize_id: null,
//         transaction_no: "123456789",
//         avs_result_code: "",
//         captured_amount: 200,
//         refunded_amount: 200,
//         merchant_txn_ref: "342287353",
//         migs_transaction: {
//           id: "342287353",
//           stan: "157245",
//           type: "REFUND",
//           amount: 200,
//           source: "INTERNET",
//           receipt: "525421157245",
//           acquirer: [Object],
//           currency: "EGP",
//           terminal: "BMNF0506",
//         },
//         acq_response_code: "00",
//         authorised_amount: 200,
//         txn_response_code: "APPROVED",
//         avs_acq_response_code: "00",
//         gateway_integration_pk: 4867403,
//       },
//       is_hidden: false,
//       payment_key_claims: null,
//       error_occured: false,
//       is_live: false,
//       other_endpoint_reference: null,
//       refunded_amount_cents: 0,
//       source_id: -1,
//       is_captured: false,
//       captured_amount: 0,
//       merchant_staff_tag: null,
//       updated_at: "2025-09-12T00:20:47.723335",
//       is_settled: false,
//       bill_balanced: false,
//       is_bill: false,
//       owner: 1862571,
//       parent_transaction: 342287022,
//     });
//     console.log("Checking rule:", r.action, "->", didMatch);
//   } catch (err) {
//     console.error("Error in rule check:", r.action, err);
//   }
// }
